server:
  port: 8080
  
awsregion: us-east-1

restful:
  timeout: 10000

url:
  servicio:
    negocio: ${hostapi}/api/negocio

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://${host}:${port}/${database}?useUnicode=true&characterEncoding=utf8&useSSL=false&requireSSL=false
    username: ${username}
    password: ${password}
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true